application: kjkblog
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*/
  script: main.py

- url: /software/sumatra
  script: main.py

- url: /software/sumatrapdf
  script: main.py

- url: /software/sumatrapdf/index.html
  script: main.py

- url: /software/sumatrapdf/download.html
  script: main.py

- url: /software/sumatrapdf/prerelase.html
  script: main.py

- url: /software/fofou
  script: main.py

- url: /articles/cocoa-objectivec-reference.html
  script: main.py

- url: /extremeoptimizations
  script: main.py

- url: /extremeoptimizations/
  script: main.py

- url: /software/sumatrapdf/sumatra-shot.*.gif
  script: main.py

- url: /software/sumatrapdf/SumatraSplash.png
  script: main.py

- url: /software
  static_dir: www/software

- url: /articles
  static_dir: www/articles

- url: /css
  static_dir: www/css

- url: /extremeoptimizations
  static_dir: www/extremeoptimizations

- url: /static/gfx
  static_dir: www/gfx
  expiration: "365d"

- url: /static/img
  static_dir: www/img

- url: /static/js
  static_dir: www/js

- url: /static
  static_dir: www/static

- url: /ckeditor
  static_dir: www/ckeditor

- url: /robots.txt
  static_files: www/robots.txt
  upload: www/robots.txt

- url: /favicon.ico
  static_files: www/static/favicon.ico
  upload: www/static/favicon.ico

- url: .*
  script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^srcblog/.*
- ^www/blog/.*
- ^scripts/.*
- ^extremeoptimizations/.*
- ^(.*/)?todo\.txt
